version: 1.0
app:
  instances: 1
  version: b54fc500-7fe2-4a23-a900-a7bc91fb10c0
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "true"
